apiVersion: v1
kind: Namespace
metadata:
  name: kube-flannel
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: flannel-psp
spec:
  privileged: true
  hostNetwork: true
  volumes:
    - '*'
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  allowedHostPaths:
    - pathPrefix: "/etc/cni/net.d"
    - pathPrefix: "/etc/kube-flannel"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
  namespace: kube-flannel
spec:
  selector:
    matchLabels:
      app: flannel
  template:
    metadata:
      labels:
        app: flannel
    spec:
      hostNetwork: true
      containers:
        - name: kube-flannel
          image: quay.io/coreos/flannel:v0.13.0-rc2
          command:
            - /opt/bin/flanneld
            - --ip-masq
            - --kube-subnet-mgr
