apiVersion: v1
kind: Namespace
metadata:
  name: hetzner-cloud
---
apiVersion: v1
kind: Secret
metadata:
  name: hcloud-token
  namespace: hetzner-cloud
type: Opaque
data:
  HCLOUD_TOKEN: SkNoR0x0NHd4OFF0ckpKdVBGSnJndDNNbHRoZXc1ekpSRkhETTdCaThWa2tYMGhsUnEzN2JUOGlROG1Zb2o5eA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcloud-cloud-controller-manager
  namespace: hetzner-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcloud-cloud-controller-manager
  template:
    metadata:
      labels:
        app: hcloud-cloud-controller-manager
    spec:
      containers:
        - name: hcloud-cloud-controller-manager
          image: hetznercloud/hcloud-cloud-controller-manager:v1.20.0
          args:
            - --cloud-provider=hetzner
          env:
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hcloud-token
                  key: HCLOUD_TOKEN
