apiVersion: v1
kind: Namespace
metadata:
  name: hetzner-cloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcloud-cloud-controller-manager
  namespace: hetzner-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcloud-cloud-controller-manager
  template:
    metadata:
      labels:
        app: hcloud-cloud-controller-manager
    spec:
      containers:
        - name: hcloud-cloud-controller-manager
          image: hetznercloud/hcloud-cloud-controller-manager:v1.10.1
          args:
            - --cloud-provider=hetzner
          env:
            - name: HCLOUD_TOKEN
              value: "<your-hcloud-token>"
