apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
        - image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.22.0
          name: cluster-autoscaler
          command:
            - ./cluster-autoscaler
            - --cloud-provider=hetzner
            - --nodes=1:10:<node-group-name>
          env:
            - name: AWS_REGION
              value: <your-region>
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
