---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cni
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cni
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  timeout: 3m0s
  wait: true
